services:
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  motivation-backend:
    image: ghcr.io/solairefr/motivation-backend:latest
    container_name: motivation-backend
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      MONGODB_URI: ${MONGODB_URI}
      SWAGGER_TITLE: ${SWAGGER_TITLE}
      SWAGGER_DESCRIPTION: ${SWAGGER_DESCRIPTION}
      SWAGGER_VERSION: ${SWAGGER_VERSION}
      SWAGGER_PATH: ${SWAGGER_PATH}

  motivation-frontend:
    image: ghcr.io/solairefr/motivation-frontend:latest
    container_name: motivation-frontend
    restart: unless-stopped
    ports:
      - 4200:80
    depends_on:
      - motivation-backend

volumes:
  mongodb_data: 