name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # ou ton nom de branche
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push FRONT image
        run: |
          cd /motivation-frontend
          docker build -t ghcr.io/solairefr/motivation-frontend:latest .
          docker push ghcr.io/solairefr/motivation-frontend:latest

      - name: Build and push BACK image
        run: |
          cd /motivation-backend
          docker build -t ghcr.io/solairefr/motivation-backend:latest .
          docker push ghcr.io/solairefr/motivation-backend:latest
